models:
  pk-app-icon:
    loader: FileLoader
    data:
      repo: rj-games/pk-app-icon
      file: pk-app-icon.ckpt
      config: templates/512-config-template.yaml
      symlink: True
  pk-icons:
    loader: FileLoader
    data:
      repo: rj-games/pk-icons
      file: pk-icons.ckpt
      config: templates/768-config-template.yaml
      symlink: True
  pk-avatars:
    loader: FileLoader
    data:
      repo: rj-games/pk-heroes-v2
      file: pk-heroes-v2.ckpt
      config: templates/768-config-template.yaml
      symlink: True
  pk-art:
    loader: FileLoader
    data:
      repo: rj-games/pk-art-v2
      file: pk-art-v2.ckpt
      config: templates/768-config-template.yaml
      symlink: True
  pk-emoji:
    loader: FileLoader
    data:
      repo: rj-games/pk-emoji
      file: pk-emoji.ckpt
      config: templates/768-config-template.yaml
      symlink: True
  pk-icons-ui:
    loader: FileLoader
    data:
      repo: rj-games/pk-icons-ui
      file: pk-icons-ui.ckpt
      config: templates/768-config-template.yaml
      symlink: True
  sd-15:
    loader: FileLoader
    data:
      repo: runwayml/stable-diffusion-v1-5
      file: v1-5-pruned-emaonly.ckpt
      config: templates/512-config-template.yaml
      symlink: True