models:
  pk-app-icon-512:
    loader: FileLoader
    data:
      repo: rj-games/pk-app-icon
      file: pk-app-icon.safetensors
      config: templates/512-config-template.yaml
      symlink: True
  pk-icons-768:
    loader: FileLoader
    data:
      repo: rj-games/pk-icons
      file: pk-icons.safetensors
      config: templates/768-config-template.yaml
      symlink: True
  pk-avatars-768:
    loader: FileLoader
    data:
      repo: rj-games/pk-heroes-v2
      file: pk-heroes-v2.safetensors
      config: templates/768-config-template.yaml
      symlink: True
  pk-art-768:
    loader: FileLoader
    data:
      repo: rj-games/pk-art-v2
      file: pk-art-v2.safetensors
      config: templates/768-config-template.yaml
      symlink: True
  pk-emoji-768:
    loader: FileLoader
    data:
      repo: rj-games/pk-emoji
      file: pk-emoji.safetensors
      config: templates/768-config-template.yaml
      symlink: True
  pk-icons-ui-768:
    loader: FileLoader
    data:
      repo: rj-games/pk-icons-ui
      file: pk-icons-ui.safetensors
      config: templates/768-config-template.yaml
      symlink: True
  sd-15-512:
    loader: FileLoader
    data:
      repo: runwayml/stable-diffusion-v1-5
      file: v1-5-pruned-emaonly.safetensors
      config: templates/512-config-template.yaml
      symlink: True
  sd-xl-base-1024:
    loader: FileLoader
    data:
      repo: stabilityai/stable-diffusion-xl-base-1.0
      file: sd_xl_base_1.0.safetensors
      config: templates/1024-config-template.yaml
      symlink: True
  sd-xl-refiner-1024:
    loader: FileLoader
    data:
      repo: stabilityai/stable-diffusion-xl-refiner-1.0
      file: sd_xl_refiner_1.0.safetensors
      config: templates/1024-config-template.yaml
      symlink: True
      