models:
  pk-icons:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-icons
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-heroes:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-heroes-v2
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-art-v2:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-art-v2
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-emoji:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-emoji
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-icons-ui:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-icons-ui
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-app-icon:
    loader: CheckpointLoader
    data:
      repo: gamma-omg/pk-app-icon
      file: pk-app-icon.ckpt
      config: templates/512-config-template.yaml
  sd-15:
    loader: CheckpointLoader
    data:
      repo: runwayml/stable-diffusion-v1-5
      file: v1-5-pruned-emaonly.ckpt
      config: templates/512-config-template.yaml