models:
  control_sd15_canny:
    loader: FileLoader
    data:
      repo: lllyasviel/ControlNet
      file: models/control_sd15_canny.pth
      symlink: True
  control_sd15_openpose:
    loader: FileLoader
    data:
      repo: lllyasviel/ControlNet
      file: models/control_sd15_openpose.pth
      symlink: True
  control_sd15_scribble:
    loader: FileLoader
    data:
      repo: lllyasviel/ControlNet
      file: models/control_sd15_scribble.pth
      symlink: True