models:
  pk-icons:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-icons
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-heroes:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-heroes-v2
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-art-v2:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-art-v2
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-emoji:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-emoji
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False
  pk-icons-ui:
    loader: DiffusersLoader
    data:
      model_name: gamma-omg/pk-icons-ui
      config: templates/768-config-template.yaml
      half: True
      use_safetensors: False